controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    drive_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

drive_cont:
  ros__parameters:

    publish_rate: 50.0
    base_frame_id: base_link
    enable_odom_tf: true

    left_wheel_names: ['left_rear_wheel_joint', 'left_front_wheel_joint']
    right_wheel_names: ['right_rear_wheel_joint', 'right_front_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.1
    wheel_base: 0.4

    wheel_separation_multiplier: 1.5

    use_stamped_vel: true

