<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>



    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- CHASSIS LINK -->
    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 ${body_height/4}"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${body_height/4}"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}">
            <origin xyz="0 0 ${body_height/4}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis_link">
        <material>Gazebo/White</material>
    </gazebo>
    
    <!-- LEFT REAR WHEEL LINK -->

    <link name="left_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT REAR WHEEL LINK -->

    <link name="right_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT FRONT WHEEL LINK -->

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT FRONT WHEEL LINK -->

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CHASSIS JOINT -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <!-- LEFT REAR WHEEL JOINT -->

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_rear_wheel"/>
        <origin xyz="-${wheel_spacing/2} ${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <!-- RIGHT REAR WHEEL JOINT -->

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_rear_wheel"/>
        <origin xyz="-${wheel_spacing/2} -${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <!-- LEFT FRONT WHEEL JOINT -->

    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="${wheel_spacing/2} ${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <!-- RIGHT FRONT WHEEL JOINT -->

    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="${wheel_spacing/2} -${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>
    
    
</robot>